name: Build and Deploy to Coolify

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/1 * * * *"  # Adjust this to the frequency you need

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy to Coolify
        env:
          COOLIFY_WEBHOOK: ${{ secrets.COOLIFY_WEBHOOK }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: |
          curl --request GET "${{ env.COOLIFY_WEBHOOK }}" \
          --header "Authorization: Bearer ${{ env.COOLIFY_TOKEN }}"