name: Build and Deploy to Coolify

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/1 * * * *"  # Adjust this to the frequency you need

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build the Astro site
        run: npm run build

      - name: Deploy to Coolify
        env:
          COOLIFY_WEBHOOK: ${{ secrets.COOLIFY_WEBHOOK }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: |
          curl --request GET "${{ env.COOLIFY_WEBHOOK }}" \
          --header "Authorization: Bearer ${{ env.COOLIFY_TOKEN }}"